apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment1
  namespace: athena
  labels:
    app: client1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1
  template:
    metadata:
      labels:
        app: client1
    spec:
      schedulerName: athena-scheduler      
      containers:
      - name: ubuntu
        image: khv129/app3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
