---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wendy-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
#    rbac.authorization.k8s.io/aggregate-to-admin: "true"
#    rbac.authorization.k8s.io/aggregate-to-edit: "true"
#    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: wendy-scheduler-clusterrolebinding
#  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
#  apiGroup: ""
  kind: ClusterRole
#  name: system:wendy-scheduler
  name: cluster-admin-2
subjects:
- kind: ServiceAccount
  name: wendy-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
#  name: system:wendy-scheduler
  name: cluster-admin-2
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - wendy-scheduler
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - pods/binding
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - delete
  - update
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wendy-scheduler
  namespace: kube-system
  labels:
    k8s-app: wendy-scheduler
spec:
  selector:
    matchLabels:
      k8s-app: wendy-scheduler
  template:
    metadata:
      name: wendy-scheduler
      labels:
        k8s-app: wendy-scheduler
    spec:
      serviceAccountName: wendy-scheduler
      volumes:
      - name: tmp-dir
        emptyDir: {}
      containers:
      - name: wendy-scheduler
        image: wenxinmmb/kube-client:v5
